name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build and push images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/weather-backend ./backend
        docker build -t ${{ secrets.DOCKERHUB_USER }}/weather-frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USER }}/weather-backend
        docker push ${{ secrets.DOCKERHUB_USER }}/weather-frontend

    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/weather-backend
          docker pull ${{ secrets.DOCKERHUB_USER }}/weather-frontend
          docker stop backend frontend || true && docker rm backend frontend || true
          docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKERHUB_USER }}/weather-backend
          docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USER }}/weather-frontend
